### PR TITLE
N pailoor planet border

### PR DESCRIPTION
**Pull request by NPailoor**

### CODE REVIEW

**Comment by novalex98** [comment]
What does the second constructor do?

**Comment by NPailoor** [comment]
Second constructor is for when the border is at the edge of the tile, and as a result does not have both spaces defined yet.

**Comment by novalex98** [comment]
Why the         if (B.canRefuel()) { section? You roll for planetary shields regardless of which way you go

**Comment by NPailoor** [comment]
Oh huh, if that's the case I'll edit it.

**Comment by novalex98** [comment]
B.shipEnter(s); is not guaranteed. If you roll less than 11 you take damage and DON'T enter

**Pull request merged**
